'use client';
import { useEffect, useState } from 'react';

type Lang = 'en' | 'hi' | 'pa' | 'ur' | 'bn';

const TRANSLATIONS: Record<Exclude<Lang, 'en'>, Record<string, string>> = {
  hi: {
    'District Court Lawyer': 'जिला न्यायालय अधिवक्ता',
    About: 'परिचय',
    'Practice Areas': 'अभ्यास क्षेत्र',
    Process: 'प्रक्रिया',
    Contact: 'संपर्क',
    'Book Consultation': 'परामर्श बुक करें',
    'District Unnao, Uttar Pradesh': 'जिला उन्नाव, उत्तर प्रदेश',
    '⌖ District Unnao, Uttar Pradesh': '⌖ जिला उन्नाव, उत्तर प्रदेश',
    '⚖ "Your Rights • Our Responsibility"': '⚖ "आपके अधिकार • हमारी जिम्मेदारी"',
    '📍 Office Chamber: Near SDM Judicial Court Collectorate, Kachari Parisar, Unnao, Uttar Pradesh 209801': '📍 कार्यालय कक्ष: एसडीएम न्यायिक न्यायालय कलेक्ट्रेट के पास, कचहरी परिसर, उन्नाव, उत्तर प्रदेश 209801',
    '💬 WhatsApp': '💬 व्हाट्सऐप',
    '🔍 View Fullscreen': '🔍 पूरी स्क्रीन में देखें',
    '◷ By appointment': '◷ पूर्व नियुक्ति द्वारा',
    'Advocate Achche Lal Gautam (LL.B.)': 'अधिवक्ता अच्छे लाल गौतम (एलएल.बी.)',
    'Justice with': 'न्याय के साथ',
    'clarity.': 'स्पष्टता।',
    'I am': 'मैं',
    ', a District Court Lawyer in Unnao. I assist clients across criminal, land & property, matrimonial, civil and related legal matters.': 'उन्नाव में जिला न्यायालय का अधिवक्ता हूँ। मैं आपराधिक, भूमि एवं संपत्ति, वैवाहिक, दीवानी और संबंधित कानूनी मामलों में सहायता करता हूँ।',
    'Request Consultation →': 'परामर्श का अनुरोध करें →',
    'Explore Practice Areas': 'अभ्यास क्षेत्र देखें',
    'Direct consultation': 'प्रत्यक्ष परामर्श',
    'Court representation': 'न्यायालय में प्रतिनिधित्व',
    'Case-focused strategy': 'मामला-केंद्रित रणनीति',
    'District Court • Unnao': 'जिला न्यायालय • उन्नाव',
    'Legal matters,': 'कानूनी मामले,',
    'presented clearly.': 'स्पष्ट रूप से प्रस्तुत।',
    'Click any practice area book to explore it in 3D. Drag to rotate, click to open.': 'किसी भी अभ्यास क्षेत्र की पुस्तक को 3D में देखने के लिए चुनें। घुमाने के लिए खींचें और खोलने के लिए क्लिक करें।',
    'Open →': 'खोलें →',
    'Click a practice area book to view details.': 'विवरण देखने के लिए किसी अभ्यास क्षेत्र की पुस्तक चुनें।',
    'About the office': 'कार्यालय के बारे में',
    'A focused legal practice in Unnao.': 'उन्नाव में केंद्रित कानूनी अभ्यास।',
    'I work with clients who need practical legal guidance and representation in District Court matters. Every case is different, so the first step is to understand the facts, documents, timeline and legal issue.': 'मैं जिला न्यायालय के मामलों में व्यावहारिक कानूनी मार्गदर्शन और प्रतिनिधित्व चाहने वाले लोगों के साथ काम करता हूँ। हर मामला अलग होता है, इसलिए पहला कदम तथ्यों, दस्तावेज़ों, समय-सीमा और कानूनी मुद्दे को समझना है।',
    'Case preparation': 'मामले की तैयारी',
    'Organising facts, documents and the questions that matter to the proceeding.': 'मामले के लिए महत्वपूर्ण तथ्यों, दस्तावेज़ों और प्रश्नों को व्यवस्थित करना।',
    'Representation and procedural assistance for applicable District Court matters.': 'जिला न्यायालय के संबंधित मामलों में प्रतिनिधित्व और प्रक्रियात्मक सहायता।',
    'Office & Practice Glimpses': 'कार्यालय और अभ्यास की झलकियाँ',
    'Real Glimpses of Chamber, Court & Public Service': 'चैंबर, न्यायालय और जनसेवा की वास्तविक झलकियाँ',
    'Authentic moments from our Unnao chamber, High Court judicial felicitation, and grassroots legal consultations.': 'उन्नाव चैंबर, उच्च न्यायालय सम्मान समारोह और जमीनी स्तर के कानूनी परामर्श के वास्तविक क्षण।',
    'All Photos (5)': 'सभी तस्वीरें (5)',
    'Office & Chamber': 'कार्यालय और चैंबर',
    'Judicial Honor': 'न्यायिक सम्मान',
    'Public Consultations': 'जन परामर्श',
    'Office Chamber': 'कार्यालय चैंबर',
    'View Fullscreen': 'पूरी स्क्रीन में देखें',
    'Office Chamber & Consultation Center': 'कार्यालय चैंबर और परामर्श केंद्र',
    'Official chamber of Advocate Achche Lal Gautam & Advocate Rakesh Singh Chauhan with legal records, consultation desk, and registration service facilities in Unnao.': 'अधिवक्ता अच्छे लाल गौतम और अधिवक्ता राकेश सिंह चौहान का आधिकारिक चैंबर, जहाँ उन्नाव में कानूनी अभिलेख, परामर्श डेस्क और पंजीकरण सेवा सुविधाएँ उपलब्ध हैं।',
    'Chamber Entrance': 'चैंबर का प्रवेश द्वार',
    'Official Signboard': 'आधिकारिक साइनबोर्ड',
    'Client Meeting Desk': 'मुवक्किल बैठक डेस्क',
    'Chamber Consultation': 'चैंबर परामर्श',
    'Chamber Consultation Desk': 'चैंबर परामर्श डेस्क',
    'Advocate Achche Lal Gautam ready for direct client consultations and document reviews at his Unnao office desk.': 'अधिवक्ता अच्छे लाल गौतम उन्नाव कार्यालय में सीधे परामर्श और दस्तावेज़ों की समीक्षा के लिए उपलब्ध हैं।',
    'Client Desk': 'मुवक्किल डेस्क',
    'Case Review': 'मामले की समीक्षा',
    'Legal Advice': 'कानूनी सलाह',
    'High Court Judicial Felicitation': 'उच्च न्यायालय न्यायिक सम्मान समारोह',
    'Advocate Achche Lal Gautam presenting ceremonial memento and shawl honoring Hon\'ble High Court Justice Irshad Ali (Lucknow Bench) at the Oath Ceremony.': 'शपथ ग्रहण समारोह में अधिवक्ता अच्छे लाल गौतम द्वारा माननीय उच्च न्यायालय के न्यायमूर्ति इरशाद अली (लखनऊ पीठ) को स्मृति-चिह्न और शॉल भेंट करते हुए।',
    'Lucknow Bench': 'लखनऊ पीठ',
    'Hon\'ble Justice Irshad Ali': 'माननीय न्यायमूर्ति इरशाद अली',
    'Oath Ceremony': 'शपथ ग्रहण समारोह',
    'Office Consultation': 'कार्यालय परामर्श',
    'Client Consultation & Legal Advisory': 'मुवक्किल परामर्श और कानूनी सलाह',
    'Direct client consultation, case discussion, and legal document verification in progress.': 'मुवक्किल परामर्श, मामले पर चर्चा और कानूनी दस्तावेज़ों का सत्यापन जारी है।',
    'Client Advisory': 'मुवक्किल सलाह',
    'Case Discussion': 'मामले पर चर्चा',
    'Document Verification': 'दस्तावेज़ सत्यापन',
    'Lead Advocate': 'मुख्य अधिवक्ता',
    'Lead counsel handling criminal trials, land consolidation (चकबंदी), revenue appeals, and matrimonial cases with personalized guidance.': 'आपराधिक मुकदमों, चकबंदी, राजस्व अपीलों और वैवाहिक मामलों में व्यक्तिगत मार्गदर्शन देने वाले मुख्य अधिवक्ता।',
    'District Court Unnao': 'जिला न्यायालय उन्नाव',
    'Legal Counsel': 'कानूनी सलाहकार',
    'How it works': 'कार्य प्रक्रिया',
    'From first call to clear next steps.': 'पहली कॉल से अगले स्पष्ट कदम तक।',
    'Share the facts': 'तथ्य साझा करें',
    'Tell us the nature of the matter and what has happened.': 'मामले की प्रकृति और अब तक हुई घटनाओं के बारे में बताएँ।',
    'Review & consultation': 'समीक्षा और परामर्श',
    'Discuss documents, timelines and the available legal route.': 'दस्तावेज़ों, समय-सीमा और उपलब्ध कानूनी रास्ते पर चर्चा करें।',
    'Case action': 'मामले की कार्रवाई',
    'Proceed with the appropriate representation, filings or next step.': 'उचित प्रतिनिधित्व, आवेदन या अगले कदम के साथ आगे बढ़ें।',
    'Team & Mentorship': 'टीम और मार्गदर्शन',
    'Guided Legal Minds.': 'मार्गदर्शन में आगे बढ़ते कानूनी विशेषज्ञ।',
    'These advocates are my juniors. They work, learn, and grow under my direct guidance, ensuring thorough research and dedicated support for our clients.': 'ये अधिवक्ता मेरे कनिष्ठ सहयोगी हैं। वे मेरे मार्गदर्शन में काम करते, सीखते और आगे बढ़ते हैं तथा मुवक्किलों को गहन शोध और समर्पित सहायता देते हैं।',
    'LL.B. • JUNIOR ASSOCIATE': 'एलएल.बी. • कनिष्ठ सहयोगी',
    'Assisting in case preparation, legal research, and district court proceedings under continuous mentorship.': 'निरंतर मार्गदर्शन में मामले की तैयारी, कानूनी शोध और जिला न्यायालय की कार्यवाही में सहायता।',
    'Consultation': 'परामर्श',
    'Tell us about your matter.': 'अपने मामले के बारे में बताएँ।',
    'Submit a consultation request. Requests are saved in this browser and work without a server.': 'परामर्श अनुरोध भेजें। अनुरोध इसी ब्राउज़र में सहेजे जाते हैं और सर्वर के बिना काम करते हैं।',
    'By appointment': 'पूर्व नियुक्ति द्वारा',
    'Near SDM Judicial Court Collectorate, Kachari Parisar, Unnao, Uttar Pradesh 209801': 'एसडीएम न्यायिक न्यायालय कलेक्ट्रेट के पास, कचहरी परिसर, उन्नाव, उत्तर प्रदेश 209801',
    '(Chamber Helpline)': '(चैंबर हेल्पलाइन)',
    CONTACT: 'संपर्क',
    'District Court Lawyer • Unnao': 'जिला न्यायालय अधिवक्ता • उन्नाव',
    'Request a consultation →': 'परामर्श का अनुरोध करें →',
    'Achche Lal Gautam. District Court Lawyer, Unnao.': 'अच्छे लाल गौतम। जिला न्यायालय अधिवक्ता, उन्नाव।',
    'Your name': 'आपका नाम',
    'Phone number': 'फ़ोन नंबर',
    'Briefly describe your matter': 'अपने मामले का संक्षिप्त विवरण दें',
    Name: 'नाम',
    Phone: 'फ़ोन',
    'Practice area': 'अभ्यास क्षेत्र',
    'Criminal Law': 'फौजदारी कानून',
    'Land & Property': 'भूमि एवं संपत्ति',
    'Marriage & Family': 'विवाह एवं परिवार',
    'Civil Disputes': 'दीवानी विवाद',
    Other: 'अन्य',
    'Brief message': 'संक्षिप्त संदेश',
    'Saved consultation requests': 'सहेजे गए परामर्श अनुरोध',
    'No requests saved in this browser.': 'इस ब्राउज़र में कोई अनुरोध सहेजा नहीं गया है।',
    Delete: 'हटाएँ',
  },
  pa: {
    'District Court Lawyer': 'ਜ਼ਿਲ੍ਹਾ ਅਦਾਲਤ ਵਕੀਲ',
    About: 'ਬਾਰੇ',
    'Practice Areas': 'ਅਭਿਆਸ ਖੇਤਰ',
    Process: 'ਪ੍ਰਕਿਰਿਆ',
    Contact: 'ਸੰਪਰਕ',
    'Book Consultation': 'ਸਲਾਹ ਬੁੱਕ ਕਰੋ',
    'District Unnao, Uttar Pradesh': 'ਜ਼ਿਲ੍ਹਾ ਉਨਾਓ, ਉੱਤਰ ਪ੍ਰਦੇਸ਼',
    '⌖ District Unnao, Uttar Pradesh': '⌖ ਜ਼ਿਲ੍ਹਾ ਉਨਾਓ, ਉੱਤਰ ਪ੍ਰਦੇਸ਼',
    '⚖ "Your Rights • Our Responsibility"': '⚖ "ਤੁਹਾਡੇ ਹੱਕ • ਸਾਡੀ ਜ਼ਿੰਮੇਵਾਰੀ"',
    '📍 Office Chamber: Near SDM Judicial Court Collectorate, Kachari Parisar, Unnao, Uttar Pradesh 209801': '📍 ਦਫ਼ਤਰ: ਐਸ.ਡੀ.ਐਮ. ਨਿਆਂਇਕ ਅਦਾਲਤ ਕਲੈਕਟਰੇਟ ਨੇੜੇ, ਕਚਹਿਰੀ ਪਰਿਸਰ, ਉਨਾਓ, ਉੱਤਰ ਪ੍ਰਦੇਸ਼ 209801',
    '💬 WhatsApp': '💬 ਵਟਸਐਪ',
    '🔍 View Fullscreen': '🔍 ਪੂਰੀ ਸਕ੍ਰੀਨ ਵਿੱਚ ਵੇਖੋ',
    '◷ By appointment': '◷ ਮੁਲਾਕਾਤ ਤੈਅ ਕਰਕੇ',
    'Advocate Achche Lal Gautam (LL.B.)': 'ਐਡਵੋਕੇਟ ਅੱਛੇ ਲਾਲ ਗੌਤਮ (ਐਲ.ਐਲ.ਬੀ.)',
    'Justice with': 'ਇਨਸਾਫ਼',
    'clarity.': 'ਸਪਸ਼ਟਤਾ ਨਾਲ।',
    'I am': 'ਮੈਂ',
    ', a District Court Lawyer in Unnao. I assist clients across criminal, land & property, matrimonial, civil and related legal matters.': ', ਉਨਾਓ ਵਿੱਚ ਜ਼ਿਲ੍ਹਾ ਅਦਾਲਤ ਦਾ ਵਕੀਲ ਹਾਂ। ਮੈਂ ਫੌਜਦਾਰੀ, ਜ਼ਮੀਨ-ਜਾਇਦਾਦ, ਵਿਆਹਕ, ਦੀਵਾਨੀ ਅਤੇ ਹੋਰ ਕਾਨੂੰਨੀ ਮਾਮਲਿਆਂ ਵਿੱਚ ਸਹਾਇਤਾ ਕਰਦਾ ਹਾਂ।',
    'Request Consultation →': 'ਸਲਾਹ ਲਈ ਬੇਨਤੀ ਕਰੋ →',
    'Explore Practice Areas': 'ਕਾਨੂੰਨੀ ਖੇਤਰ ਵੇਖੋ',
    'Direct consultation': 'ਸਿੱਧੀ ਸਲਾਹ',
    'Court representation': 'ਅਦਾਲਤ ਵਿੱਚ ਨੁਮਾਇੰਦਗੀ',
    'Case-focused strategy': 'ਮੁਕੱਦਮੇ ਲਈ ਰਣਨੀਤੀ',
    'District Court • Unnao': 'ਜ਼ਿਲ੍ਹਾ ਅਦਾਲਤ • ਉਨਾਓ',
    'Legal matters,': 'ਕਾਨੂੰਨੀ ਮਾਮਲੇ,',
    'presented clearly.': 'ਸਪਸ਼ਟ ਢੰਗ ਨਾਲ ਪੇਸ਼।',
    'Click any practice area book to explore it in 3D. Drag to rotate, click to open.': 'ਕਿਸੇ ਵੀ ਕਾਨੂੰਨੀ ਖੇਤਰ ਦੀ ਕਿਤਾਬ ਨੂੰ 3D ਵਿੱਚ ਵੇਖਣ ਲਈ ਚੁਣੋ। ਘੁਮਾਉਣ ਲਈ ਖਿੱਚੋ ਅਤੇ ਖੋਲ੍ਹਣ ਲਈ ਕਲਿੱਕ ਕਰੋ।',
    'Open →': 'ਖੋਲ੍ਹੋ →',
    'Click a practice area book to view details.': 'ਵੇਰਵੇ ਵੇਖਣ ਲਈ ਕਾਨੂੰਨੀ ਖੇਤਰ ਦੀ ਕਿਤਾਬ ਚੁਣੋ।',
    'About the office': 'ਦਫ਼ਤਰ ਬਾਰੇ',
    'A focused legal practice in Unnao.': 'ਉਨਾਓ ਵਿੱਚ ਕੇਂਦਰਿਤ ਕਾਨੂੰਨੀ ਸੇਵਾ।',
    'I work with clients who need practical legal guidance and representation in District Court matters. Every case is different, so the first step is to understand the facts, documents, timeline and legal issue.': 'ਮੈਂ ਜ਼ਿਲ੍ਹਾ ਅਦਾਲਤ ਦੇ ਮਾਮਲਿਆਂ ਵਿੱਚ ਵਿਹਾਰਕ ਕਾਨੂੰਨੀ ਸਲਾਹ ਅਤੇ ਨੁਮਾਇੰਦਗੀ ਲੋੜਨ ਵਾਲੇ ਲੋਕਾਂ ਨਾਲ ਕੰਮ ਕਰਦਾ ਹਾਂ। ਹਰ ਮਾਮਲਾ ਵੱਖਰਾ ਹੁੰਦਾ ਹੈ, ਇਸ ਲਈ ਪਹਿਲਾਂ ਤੱਥਾਂ, ਦਸਤਾਵੇਜ਼ਾਂ, ਸਮਾਂ-ਸੀਮਾ ਅਤੇ ਕਾਨੂੰਨੀ ਮੁੱਦੇ ਨੂੰ ਸਮਝਣਾ ਜ਼ਰੂਰੀ ਹੈ।',
    'Case preparation': 'ਮੁਕੱਦਮੇ ਦੀ ਤਿਆਰੀ',
    'Organising facts, documents and the questions that matter to the proceeding.': 'ਕਾਰਵਾਈ ਲਈ ਮਹੱਤਵਪੂਰਨ ਤੱਥਾਂ, ਦਸਤਾਵੇਜ਼ਾਂ ਅਤੇ ਸਵਾਲਾਂ ਨੂੰ ਤਰਤੀਬ ਦੇਣਾ।',
    'Representation and procedural assistance for applicable District Court matters.': 'ਸੰਬੰਧਿਤ ਜ਼ਿਲ੍ਹਾ ਅਦਾਲਤੀ ਮਾਮਲਿਆਂ ਵਿੱਚ ਨੁਮਾਇੰਦਗੀ ਅਤੇ ਪ੍ਰਕਿਰਿਆਤਮਕ ਸਹਾਇਤਾ।',
    'Office & Practice Glimpses': 'ਦਫ਼ਤਰ ਅਤੇ ਕੰਮ ਦੀਆਂ ਝਲਕਾਂ',
    'Real Glimpses of Chamber, Court & Public Service': 'ਚੈਂਬਰ, ਅਦਾਲਤ ਅਤੇ ਜਨ ਸੇਵਾ ਦੀਆਂ ਅਸਲ ਝਲਕਾਂ',
    'Authentic moments from our Unnao chamber, High Court judicial felicitation, and grassroots legal consultations.': 'ਉਨਾਓ ਚੈਂਬਰ, ਹਾਈ ਕੋਰਟ ਦੇ ਸਨਮਾਨ ਸਮਾਰੋਹ ਅਤੇ ਜ਼ਮੀਨੀ ਪੱਧਰ ਦੀ ਕਾਨੂੰਨੀ ਸਲਾਹ ਦੇ ਅਸਲ ਪਲ।',
    'All Photos (5)': 'ਸਾਰੀਆਂ ਤਸਵੀਰਾਂ (5)',
    'Office & Chamber': 'ਦਫ਼ਤਰ ਅਤੇ ਚੈਂਬਰ',
    'Judicial Honor': 'ਨਿਆਂਇਕ ਸਨਮਾਨ',
    'Public Consultations': 'ਜਨਤਕ ਸਲਾਹ-ਮਸ਼ਵਰਾ',
    'Office Chamber': 'ਦਫ਼ਤਰੀ ਚੈਂਬਰ',
    'View Fullscreen': 'ਪੂਰੀ ਸਕ੍ਰੀਨ ਵਿੱਚ ਵੇਖੋ',
    'Office Chamber & Consultation Center': 'ਦਫ਼ਤਰੀ ਚੈਂਬਰ ਅਤੇ ਸਲਾਹ ਕੇਂਦਰ',
    'Official chamber of Advocate Achche Lal Gautam & Advocate Rakesh Singh Chauhan with legal records, consultation desk, and registration service facilities in Unnao.': 'ਐਡਵੋਕੇਟ ਅੱਛੇ ਲਾਲ ਗੌਤਮ ਅਤੇ ਐਡਵੋਕੇਟ ਰਾਕੇਸ਼ ਸਿੰਘ ਚੌਹਾਨ ਦਾ ਅਧਿਕਾਰਤ ਚੈਂਬਰ, ਜਿੱਥੇ ਉਨਾਓ ਵਿੱਚ ਕਾਨੂੰਨੀ ਰਿਕਾਰਡ, ਸਲਾਹ ਡੈਸਕ ਅਤੇ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਸੇਵਾਵਾਂ ਉਪਲਬਧ ਹਨ।',
    'Chamber Entrance': 'ਚੈਂਬਰ ਦਾ ਦਰਵਾਜ਼ਾ',
    'Official Signboard': 'ਅਧਿਕਾਰਤ ਸਾਈਨਬੋਰਡ',
    'Client Meeting Desk': 'ਮੁਵੱਕਲ ਮਿਲਣੀ ਡੈਸਕ',
    'Chamber Consultation': 'ਚੈਂਬਰ ਸਲਾਹ',
    'Chamber Consultation Desk': 'ਚੈਂਬਰ ਸਲਾਹ ਡੈਸਕ',
    'Advocate Achche Lal Gautam ready for direct client consultations and document reviews at his Unnao office desk.': 'ਐਡਵੋਕੇਟ ਅੱਛੇ ਲਾਲ ਗੌਤਮ ਆਪਣੇ ਉਨਾਓ ਦਫ਼ਤਰ ਵਿੱਚ ਸਿੱਧੀ ਸਲਾਹ ਅਤੇ ਦਸਤਾਵੇਜ਼ਾਂ ਦੀ ਸਮੀਖਿਆ ਲਈ ਉਪਲਬਧ ਹਨ।',
    'Client Desk': 'ਮੁਵੱਕਲ ਡੈਸਕ',
    'Case Review': 'ਮਾਮਲੇ ਦੀ ਸਮੀਖਿਆ',
    'Legal Advice': 'ਕਾਨੂੰਨੀ ਸਲਾਹ',
    'High Court Judicial Felicitation': 'ਹਾਈ ਕੋਰਟ ਨਿਆਂਇਕ ਸਨਮਾਨ ਸਮਾਰੋਹ',
    'Advocate Achche Lal Gautam presenting ceremonial memento and shawl honoring Hon\'ble High Court Justice Irshad Ali (Lucknow Bench) at the Oath Ceremony.': 'ਸਹੁੰ ਚੁੱਕ ਸਮਾਰੋਹ ਵਿੱਚ ਐਡਵੋਕੇਟ ਅੱਛੇ ਲਾਲ ਗੌਤਮ ਵੱਲੋਂ ਮਾਨਯੋਗ ਹਾਈ ਕੋਰਟ ਜਸਟਿਸ ਇਰਸ਼ਾਦ ਅਲੀ (ਲਖਨਊ ਬੈਂਚ) ਨੂੰ ਯਾਦਗਾਰੀ ਚਿੰਨ੍ਹ ਅਤੇ ਸ਼ਾਲ ਭੇਟ।',
    'Lucknow Bench': 'ਲਖਨਊ ਬੈਂਚ',
    'Hon\'ble Justice Irshad Ali': 'ਮਾਨਯੋਗ ਜਸਟਿਸ ਇਰਸ਼ਾਦ ਅਲੀ',
    'Oath Ceremony': 'ਸਹੁੰ ਚੁੱਕ ਸਮਾਰੋਹ',
    'Office Consultation': 'ਦਫ਼ਤਰੀ ਸਲਾਹ',
    'Client Consultation & Legal Advisory': 'ਮੁਵੱਕਲ ਸਲਾਹ ਅਤੇ ਕਾਨੂੰਨੀ ਮਾਰਗਦਰਸ਼ਨ',
    'Direct client consultation, case discussion, and legal document verification in progress.': 'ਸਿੱਧੀ ਮੁਵੱਕਲ ਸਲਾਹ, ਮਾਮਲੇ ਬਾਰੇ ਚਰਚਾ ਅਤੇ ਕਾਨੂੰਨੀ ਦਸਤਾਵੇਜ਼ਾਂ ਦੀ ਜਾਂਚ ਜਾਰੀ ਹੈ।',
    'Client Advisory': 'ਮੁਵੱਕਲ ਮਾਰਗਦਰਸ਼ਨ',
    'Case Discussion': 'ਮਾਮਲੇ ਬਾਰੇ ਚਰਚਾ',
    'Document Verification': 'ਦਸਤਾਵੇਜ਼ ਜਾਂਚ',
    'Lead Advocate': 'ਮੁੱਖ ਵਕੀਲ',
    'Lead counsel handling criminal trials, land consolidation (चकबंदी), revenue appeals, and matrimonial cases with personalized guidance.': 'ਫੌਜਦਾਰੀ ਮੁਕੱਦਮਿਆਂ, ਚਕਬੰਦੀ, ਮਾਲੀਆ ਅਪੀਲਾਂ ਅਤੇ ਵਿਆਹਕ ਮਾਮਲਿਆਂ ਵਿੱਚ ਨਿੱਜੀ ਮਾਰਗਦਰਸ਼ਨ ਦੇਣ ਵਾਲੇ ਮੁੱਖ ਵਕੀਲ।',
    'District Court Unnao': 'ਜ਼ਿਲ੍ਹਾ ਅਦਾਲਤ ਉਨਾਓ',
    'Legal Counsel': 'ਕਾਨੂੰਨੀ ਸਲਾਹਕਾਰ',
    'How it works': 'ਕੰਮ ਕਰਨ ਦਾ ਤਰੀਕਾ',
    'From first call to clear next steps.': 'ਪਹਿਲੀ ਕਾਲ ਤੋਂ ਅਗਲੇ ਸਪਸ਼ਟ ਕਦਮ ਤੱਕ।',
    'Share the facts': 'ਤੱਥ ਸਾਂਝੇ ਕਰੋ',
    'Tell us the nature of the matter and what has happened.': 'ਮਾਮਲੇ ਦੀ ਕਿਸਮ ਅਤੇ ਹੁਣ ਤੱਕ ਕੀ ਹੋਇਆ ਹੈ, ਦੱਸੋ।',
    'Review & consultation': 'ਸਮੀਖਿਆ ਅਤੇ ਸਲਾਹ',
    'Discuss documents, timelines and the available legal route.': 'ਦਸਤਾਵੇਜ਼ਾਂ, ਸਮਾਂ-ਸੀਮਾਵਾਂ ਅਤੇ ਉਪਲਬਧ ਕਾਨੂੰਨੀ ਰਾਹ ਬਾਰੇ ਗੱਲ ਕਰੋ।',
    'Case action': 'ਮਾਮਲੇ ਦੀ ਕਾਰਵਾਈ',
    'Proceed with the appropriate representation, filings or next step.': 'ਢੁਕਵੀਂ ਨੁਮਾਇੰਦਗੀ, ਅਰਜ਼ੀਆਂ ਜਾਂ ਅਗਲੇ ਕਦਮ ਨਾਲ ਅੱਗੇ ਵਧੋ।',
    'Team & Mentorship': 'ਟੀਮ ਅਤੇ ਮਾਰਗਦਰਸ਼ਨ',
    'Guided Legal Minds.': 'ਮਾਰਗਦਰਸ਼ਨ ਹੇਠ ਕਾਨੂੰਨੀ ਮਾਹਿਰ।',
    'These advocates are my juniors. They work, learn, and grow under my direct guidance, ensuring thorough research and dedicated support for our clients.': 'ਇਹ ਵਕੀਲ ਮੇਰੇ ਜੂਨੀਅਰ ਹਨ। ਉਹ ਮੇਰੀ ਸਿੱਧੀ ਰਹਿਨੁਮਾਈ ਹੇਠ ਕੰਮ ਕਰਦੇ, ਸਿੱਖਦੇ ਅਤੇ ਤਰੱਕੀ ਕਰਦੇ ਹਨ ਅਤੇ ਮੁਵੱਕਲਾਂ ਨੂੰ ਡੂੰਘੀ ਖੋਜ ਤੇ ਸਮਰਪਿਤ ਸਹਾਇਤਾ ਦਿੰਦੇ ਹਨ।',
    'LL.B. • JUNIOR ASSOCIATE': 'ਐਲ.ਐਲ.ਬੀ. • ਜੂਨੀਅਰ ਸਹਿਯੋਗੀ',
    'Assisting in case preparation, legal research, and district court proceedings under continuous mentorship.': 'ਲਗਾਤਾਰ ਰਹਿਨੁਮਾਈ ਹੇਠ ਮੁਕੱਦਮੇ ਦੀ ਤਿਆਰੀ, ਕਾਨੂੰਨੀ ਖੋਜ ਅਤੇ ਜ਼ਿਲ੍ਹਾ ਅਦਾਲਤੀ ਕਾਰਵਾਈ ਵਿੱਚ ਸਹਾਇਤਾ।',
    'Consultation': 'ਸਲਾਹ-ਮਸ਼ਵਰਾ',
    'Tell us about your matter.': 'ਆਪਣੇ ਮਾਮਲੇ ਬਾਰੇ ਦੱਸੋ।',
    'Submit a consultation request. Requests are saved in this browser and work without a server.': 'ਸਲਾਹ ਦੀ ਬੇਨਤੀ ਭੇਜੋ। ਬੇਨਤੀਆਂ ਇਸ ਬ੍ਰਾਊਜ਼ਰ ਵਿੱਚ ਸੁਰੱਖਿਅਤ ਹੁੰਦੀਆਂ ਹਨ ਅਤੇ ਸਰਵਰ ਤੋਂ ਬਿਨਾਂ ਕੰਮ ਕਰਦੀਆਂ ਹਨ।',
    'By appointment': 'ਮੁਲਾਕਾਤ ਤੈਅ ਕਰਕੇ',
    'Near SDM Judicial Court Collectorate, Kachari Parisar, Unnao, Uttar Pradesh 209801': 'ਐਸ.ਡੀ.ਐਮ. ਨਿਆਂਇਕ ਅਦਾਲਤ ਕਲੈਕਟਰੇਟ ਨੇੜੇ, ਕਚਹਿਰੀ ਪਰਿਸਰ, ਉਨਾਓ, ਉੱਤਰ ਪ੍ਰਦੇਸ਼ 209801',
    '(Chamber Helpline)': '(ਚੈਂਬਰ ਹੈਲਪਲਾਈਨ)',
    CONTACT: 'ਸੰਪਰਕ',
    'District Court Lawyer • Unnao': 'ਜ਼ਿਲ੍ਹਾ ਅਦਾਲਤ ਵਕੀਲ • ਉਨਾਓ',
    'Request a consultation →': 'ਸਲਾਹ ਲਈ ਬੇਨਤੀ ਕਰੋ →',
    'Achche Lal Gautam. District Court Lawyer, Unnao.': 'ਅੱਛੇ ਲਾਲ ਗੌਤਮ। ਜ਼ਿਲ੍ਹਾ ਅਦਾਲਤ ਵਕੀਲ, ਉਨਾਓ।',
    'Your name': 'ਤੁਹਾਡਾ ਨਾਮ',
    'Phone number': 'ਫ਼ੋਨ ਨੰਬਰ',
    'Briefly describe your matter': 'ਆਪਣੇ ਮਾਮਲੇ ਦਾ ਸੰਖੇਪ ਵੇਰਵਾ ਦਿਓ',
    Name: 'ਨਾਮ',
    Phone: 'ਫ਼ੋਨ',
    'Practice area': 'ਕਾਨੂੰਨੀ ਖੇਤਰ',
    'Criminal Law': 'ਫੌਜਦਾਰੀ ਕਾਨੂੰਨ',
    'Land & Property': 'ਜ਼ਮੀਨ ਅਤੇ ਜਾਇਦਾਦ',
    'Marriage & Family': 'ਵਿਆਹ ਅਤੇ ਪਰਿਵਾਰ',
    'Civil Disputes': 'ਦੀਵਾਨੀ ਝਗੜੇ',
    Other: 'ਹੋਰ',
    'Brief message': 'ਸੰਖੇਪ ਸੁਨੇਹਾ',
    'Saved consultation requests': 'ਸੰਭਾਲੀਆਂ ਸਲਾਹ ਬੇਨਤੀਆਂ',
    'No requests saved in this browser.': 'ਇਸ ਬ੍ਰਾਊਜ਼ਰ ਵਿੱਚ ਕੋਈ ਬੇਨਤੀ ਸੰਭਾਲੀ ਨਹੀਂ ਹੈ।',
    Delete: 'ਮਿਟਾਓ',
  },
  ur: {
    'District Court Lawyer': 'ضلعی عدالت وکیل',
    About: 'تعارف',
    'Practice Areas': 'پریکٹس کے شعبے',
    Process: 'عمل',
    Contact: 'رابطہ',
    'Book Consultation': 'مشاورت بک کریں',
    'District Unnao, Uttar Pradesh': 'ضلع اناؤ، اتر پردیش',
    '⌖ District Unnao, Uttar Pradesh': '⌖ ضلع اناؤ، اتر پردیش',
    '⚖ "Your Rights • Our Responsibility"': '⚖ "آپ کے حقوق • ہماری ذمہ داری"',
    '📍 Office Chamber: Near SDM Judicial Court Collectorate, Kachari Parisar, Unnao, Uttar Pradesh 209801': '📍 دفتر: ایس ڈی ایم جوڈیشل کورٹ کلیکٹریٹ کے قریب، کچہری پریسر، اناؤ، اتر پردیش 209801',
    '💬 WhatsApp': '💬 واٹس ایپ',
    '🔍 View Fullscreen': '🔍 پوری اسکرین میں دیکھیں',
    '◷ By appointment': '◷ پیشگی وقت لے کر',
    'Advocate Achche Lal Gautam (LL.B.)': 'ایڈووکیٹ اچھے لال گوتم (ایل ایل بی)',
    'Justice with': 'انصاف',
    'clarity.': 'وضاحت کے ساتھ۔',
    'I am': 'میں',
    ', a District Court Lawyer in Unnao. I assist clients across criminal, land & property, matrimonial, civil and related legal matters.': '، اناؤ میں ضلعی عدالت کا وکیل ہوں۔ میں فوجداری، زمین و جائیداد، ازدواجی، دیوانی اور متعلقہ قانونی معاملات میں مؤکلوں کی مدد کرتا ہوں۔',
    'Request Consultation →': 'مشاورت کی درخواست کریں ←',
    'Explore Practice Areas': 'قانونی شعبے دیکھیں',
    'Direct consultation': 'براہ راست مشاورت',
    'Court representation': 'عدالت میں نمائندگی',
    'Case-focused strategy': 'مقدمے کے لیے حکمت عملی',
    'District Court • Unnao': 'ضلعی عدالت • اناؤ',
    'Legal matters,': 'قانونی معاملات،',
    'presented clearly.': 'واضح انداز میں پیش۔',
    'Click any practice area book to explore it in 3D. Drag to rotate, click to open.': 'کسی بھی قانونی شعبے کی کتاب کو 3D میں دیکھنے کے لیے منتخب کریں۔ گھمانے کے لیے کھینچیں اور کھولنے کے لیے کلک کریں۔',
    'Open →': 'کھولیں ←',
    'Click a practice area book to view details.': 'تفصیلات دیکھنے کے لیے قانونی شعبے کی کتاب منتخب کریں۔',
    'About the office': 'دفتر کے بارے میں',
    'A focused legal practice in Unnao.': 'اناؤ میں مرکوز قانونی خدمات۔',
    'I work with clients who need practical legal guidance and representation in District Court matters. Every case is different, so the first step is to understand the facts, documents, timeline and legal issue.': 'میں ضلعی عدالت کے معاملات میں عملی قانونی رہنمائی اور نمائندگی کے خواہش مند مؤکلوں کے ساتھ کام کرتا ہوں۔ ہر مقدمہ مختلف ہوتا ہے، اس لیے پہلا قدم حقائق، دستاویزات، مدت اور قانونی مسئلے کو سمجھنا ہے۔',
    'Case preparation': 'مقدمے کی تیاری',
    'Organising facts, documents and the questions that matter to the proceeding.': 'کارروائی کے لیے اہم حقائق، دستاویزات اور سوالات کو منظم کرنا۔',
    'Representation and procedural assistance for applicable District Court matters.': 'متعلقہ ضلعی عدالتی معاملات میں نمائندگی اور طریقۂ کار کی مدد۔',
    'Office & Practice Glimpses': 'دفتر اور کام کی جھلکیاں',
    'Real Glimpses of Chamber, Court & Public Service': 'چیمبر، عدالت اور عوامی خدمت کی حقیقی جھلکیاں',
    'Authentic moments from our Unnao chamber, High Court judicial felicitation, and grassroots legal consultations.': 'اناؤ چیمبر، ہائی کورٹ کی اعزازی تقریب اور مقامی قانونی مشاورت کے حقیقی لمحات۔',
    'All Photos (5)': 'تمام تصاویر (5)',
    'Office & Chamber': 'دفتر اور چیمبر',
    'Judicial Honor': 'عدالتی اعزاز',
    'Public Consultations': 'عوامی مشاورت',
    'Office Chamber': 'دفتر کا چیمبر',
    'View Fullscreen': 'پوری اسکرین میں دیکھیں',
    'Office Chamber & Consultation Center': 'دفتر کا چیمبر اور مشاورتی مرکز',
    'Official chamber of Advocate Achche Lal Gautam & Advocate Rakesh Singh Chauhan with legal records, consultation desk, and registration service facilities in Unnao.': 'ایڈووکیٹ اچھے لال گوتم اور ایڈووکیٹ راکیش سنگھ چوہان کا سرکاری چیمبر، جہاں اناؤ میں قانونی ریکارڈ، مشاورتی ڈیسک اور رجسٹریشن کی سہولت موجود ہے۔',
    'Chamber Entrance': 'چیمبر کا داخلی راستہ',
    'Official Signboard': 'سرکاری سائن بورڈ',
    'Client Meeting Desk': 'مؤکل ملاقات ڈیسک',
    'Chamber Consultation': 'چیمبر مشاورت',
    'Chamber Consultation Desk': 'چیمبر مشاورتی ڈیسک',
    'Advocate Achche Lal Gautam ready for direct client consultations and document reviews at his Unnao office desk.': 'ایڈووکیٹ اچھے لال گوتم اناؤ کے دفتر میں براہ راست مشاورت اور دستاویزات کے جائزے کے لیے دستیاب ہیں۔',
    'Client Desk': 'مؤکل ڈیسک',
    'Case Review': 'مقدمے کا جائزہ',
    'Legal Advice': 'قانونی مشورہ',
    'High Court Judicial Felicitation': 'ہائی کورٹ کی اعزازی تقریب',
    'Advocate Achche Lal Gautam presenting ceremonial memento and shawl honoring Hon\'ble High Court Justice Irshad Ali (Lucknow Bench) at the Oath Ceremony.': 'حلف برداری کی تقریب میں ایڈووکیٹ اچھے لال گوتم معزز ہائی کورٹ جسٹس ارشاد علی (لکھنؤ بنچ) کو یادگاری نشان اور شال پیش کرتے ہوئے۔',
    'Lucknow Bench': 'لکھنؤ بنچ',
    'Hon\'ble Justice Irshad Ali': 'معزز جسٹس ارشاد علی',
    'Oath Ceremony': 'حلف برداری کی تقریب',
    'Office Consultation': 'دفتر میں مشاورت',
    'Client Consultation & Legal Advisory': 'مؤکل کی مشاورت اور قانونی رہنمائی',
    'Direct client consultation, case discussion, and legal document verification in progress.': 'براہ راست مؤکل مشاورت، مقدمے پر گفتگو اور قانونی دستاویزات کی تصدیق جاری ہے۔',
    'Client Advisory': 'مؤکل رہنمائی',
    'Case Discussion': 'مقدمے پر گفتگو',
    'Document Verification': 'دستاویزات کی تصدیق',
    'Lead Advocate': 'سربراہ وکیل',
    'Lead counsel handling criminal trials, land consolidation (चकबंदी), revenue appeals, and matrimonial cases with personalized guidance.': 'فوجداری مقدمات، چک بندی، محصولات کی اپیلوں اور ازدواجی معاملات میں انفرادی رہنمائی فراہم کرنے والے سربراہ وکیل۔',
    'District Court Unnao': 'ضلعی عدالت اناؤ',
    'Legal Counsel': 'قانونی مشیر',
    'How it works': 'طریقۂ کار',
    'From first call to clear next steps.': 'پہلی کال سے اگلے واضح قدم تک۔',
    'Share the facts': 'حقائق بتائیں',
    'Tell us the nature of the matter and what has happened.': 'معاملے کی نوعیت اور اب تک پیش آنے والے واقعات بتائیں۔',
    'Review & consultation': 'جائزہ اور مشاورت',
    'Discuss documents, timelines and the available legal route.': 'دستاویزات، مدت اور دستیاب قانونی راستے پر بات کریں۔',
    'Case action': 'مقدمے کی کارروائی',
    'Proceed with the appropriate representation, filings or next step.': 'مناسب نمائندگی، درخواستوں یا اگلے قدم کے ساتھ آگے بڑھیں۔',
    'Team & Mentorship': 'ٹیم اور رہنمائی',
    'Guided Legal Minds.': 'رہنمائی یافتہ قانونی ماہرین۔',
    'These advocates are my juniors. They work, learn, and grow under my direct guidance, ensuring thorough research and dedicated support for our clients.': 'یہ وکلا میرے جونیئر ہیں۔ وہ میری براہ راست رہنمائی میں کام کرتے، سیکھتے اور آگے بڑھتے ہیں، اور مؤکلوں کو مکمل تحقیق اور بھرپور معاونت فراہم کرتے ہیں۔',
    'LL.B. • JUNIOR ASSOCIATE': 'ایل ایل بی • جونیئر ایسوسی ایٹ',
    'Assisting in case preparation, legal research, and district court proceedings under continuous mentorship.': 'مسلسل رہنمائی میں مقدمے کی تیاری، قانونی تحقیق اور ضلعی عدالتی کارروائی میں معاونت۔',
    'Consultation': 'مشاورت',
    'Tell us about your matter.': 'اپنے معاملے کے بارے میں بتائیں۔',
    'Submit a consultation request. Requests are saved in this browser and work without a server.': 'مشاورت کی درخواست بھیجیں۔ درخواستیں اسی براؤزر میں محفوظ ہوتی ہیں اور سرور کے بغیر کام کرتی ہیں۔',
    'By appointment': 'پیشگی وقت لے کر',
    'Near SDM Judicial Court Collectorate, Kachari Parisar, Unnao, Uttar Pradesh 209801': 'ایس ڈی ایم جوڈیشل کورٹ کلیکٹریٹ کے قریب، کچہری پریسر، اناؤ، اتر پردیش 209801',
    '(Chamber Helpline)': '(چیمبر ہیلپ لائن)',
    CONTACT: 'رابطہ',
    'District Court Lawyer • Unnao': 'ضلعی عدالت وکیل • اناؤ',
    'Request a consultation →': 'مشاورت کی درخواست کریں ←',
    'Achche Lal Gautam. District Court Lawyer, Unnao.': 'اچھے لال گوتم۔ ضلعی عدالت وکیل، اناؤ۔',
    'Your name': 'آپ کا نام',
    'Phone number': 'فون نمبر',
    'Briefly describe your matter': 'اپنے معاملے کی مختصر تفصیل دیں',
    Name: 'نام',
    Phone: 'فون',
    'Practice area': 'قانونی شعبہ',
    'Criminal Law': 'فوجداری قانون',
    'Land & Property': 'زمین و جائیداد',
    'Marriage & Family': 'شادی اور خاندان',
    'Civil Disputes': 'دیوانی تنازعات',
    Other: 'دیگر',
    'Brief message': 'مختصر پیغام',
    'Saved consultation requests': 'محفوظ مشاورتی درخواستیں',
    'No requests saved in this browser.': 'اس براؤزر میں کوئی درخواست محفوظ نہیں ہے۔',
    Delete: 'حذف کریں',
  },
  bn: {
    'District Court Lawyer': 'জেলা আদালত আইনজীবী',
    About: 'সম্পর্কে',
    'Practice Areas': 'অনুশীলন এলাকা',
    Process: 'প্রক্রিয়া',
    Contact: 'যোগাযোগ',
    'Book Consultation': 'পরামর্শ বুক করুন',
    'District Unnao, Uttar Pradesh': 'উন্নাও জেলা, উত্তর প্রদেশ',
    '⌖ District Unnao, Uttar Pradesh': '⌖ উন্নাও জেলা, উত্তর প্রদেশ',
    '⚖ "Your Rights • Our Responsibility"': '⚖ "আপনার অধিকার • আমাদের দায়িত্ব"',
    '📍 Office Chamber: Near SDM Judicial Court Collectorate, Kachari Parisar, Unnao, Uttar Pradesh 209801': '📍 অফিস চেম্বার: এসডিএম জুডিশিয়াল কোর্ট কালেক্টরেটের কাছে, কাছারি পরিসর, উন্নাও, উত্তর প্রদেশ 209801',
    '💬 WhatsApp': '💬 হোয়াটসঅ্যাপ',
    '🔍 View Fullscreen': '🔍 পূর্ণ পর্দায় দেখুন',
    '◷ By appointment': '◷ সময় নির্ধারণ করে',
    'Advocate Achche Lal Gautam (LL.B.)': 'অ্যাডভোকেট অচ্ছে লাল গৌতম (এলএল.বি.)',
    'Justice with': 'ন্যায়',
    'clarity.': 'স্বচ্ছতার সঙ্গে।',
    'I am': 'আমি',
    ', a District Court Lawyer in Unnao. I assist clients across criminal, land & property, matrimonial, civil and related legal matters.': ', উন্নাওয়ের জেলা আদালতের একজন আইনজীবী। ফৌজদারি, জমি ও সম্পত্তি, বিবাহ, দেওয়ানি এবং সংশ্লিষ্ট আইনি বিষয়ে আমি মক্কেলদের সহায়তা করি।',
    'Request Consultation →': 'পরামর্শের অনুরোধ করুন →',
    'Explore Practice Areas': 'আইনি ক্ষেত্র দেখুন',
    'Direct consultation': 'সরাসরি পরামর্শ',
    'Court representation': 'আদালতে প্রতিনিধিত্ব',
    'Case-focused strategy': 'মামলাভিত্তিক কৌশল',
    'District Court • Unnao': 'জেলা আদালত • উন্নাও',
    'Legal matters,': 'আইনি বিষয়গুলি,',
    'presented clearly.': 'স্পষ্টভাবে উপস্থাপিত।',
    'Click any practice area book to explore it in 3D. Drag to rotate, click to open.': 'যেকোনো আইনি ক্ষেত্রের বই 3D-তে দেখতে নির্বাচন করুন। ঘোরাতে টেনে আনুন, খুলতে ক্লিক করুন।',
    'Open →': 'খুলুন →',
    'Click a practice area book to view details.': 'বিস্তারিত দেখতে আইনি ক্ষেত্রের বই নির্বাচন করুন।',
    'About the office': 'অফিস সম্পর্কে',
    'A focused legal practice in Unnao.': 'উন্নাওয়ে মনোযোগী আইনি পরিষেবা।',
    'I work with clients who need practical legal guidance and representation in District Court matters. Every case is different, so the first step is to understand the facts, documents, timeline and legal issue.': 'জেলা আদালতের বিষয়ে বাস্তবসম্মত আইনি পরামর্শ ও প্রতিনিধিত্ব প্রয়োজন এমন মক্কেলদের সঙ্গে আমি কাজ করি। প্রতিটি মামলা আলাদা, তাই প্রথমে ঘটনা, নথি, সময়সীমা এবং আইনি বিষয়টি বুঝে নেওয়া জরুরি।',
    'Case preparation': 'মামলার প্রস্তুতি',
    'Organising facts, documents and the questions that matter to the proceeding.': 'মামলার কার্যক্রমের জন্য গুরুত্বপূর্ণ ঘটনা, নথি ও প্রশ্নগুলি গুছিয়ে নেওয়া।',
    'Representation and procedural assistance for applicable District Court matters.': 'প্রযোজ্য জেলা আদালতের বিষয়ে প্রতিনিধিত্ব ও প্রক্রিয়াগত সহায়তা।',
    'Office & Practice Glimpses': 'অফিস ও কাজের ঝলক',
    'Real Glimpses of Chamber, Court & Public Service': 'চেম্বার, আদালত ও জনসেবার বাস্তব ঝলক',
    'Authentic moments from our Unnao chamber, High Court judicial felicitation, and grassroots legal consultations.': 'উন্নাও চেম্বার, হাইকোর্টের সম্মাননা অনুষ্ঠান এবং তৃণমূল পর্যায়ের আইনি পরামর্শের বাস্তব মুহূর্ত।',
    'All Photos (5)': 'সব ছবি (5)',
    'Office & Chamber': 'অফিস ও চেম্বার',
    'Judicial Honor': 'বিচারিক সম্মাননা',
    'Public Consultations': 'জনপরামর্শ',
    'Office Chamber': 'অফিস চেম্বার',
    'View Fullscreen': 'পূর্ণ পর্দায় দেখুন',
    'Office Chamber & Consultation Center': 'অফিস চেম্বার ও পরামর্শ কেন্দ্র',
    'Official chamber of Advocate Achche Lal Gautam & Advocate Rakesh Singh Chauhan with legal records, consultation desk, and registration service facilities in Unnao.': 'অ্যাডভোকেট অচ্ছে লাল গৌতম ও অ্যাডভোকেট রাকেশ সিং চৌহানের অফিসিয়াল চেম্বার; এখানে উন্নাওয়ে আইনি নথি, পরামর্শ ডেস্ক ও নিবন্ধন পরিষেবার সুবিধা রয়েছে।',
    'Chamber Entrance': 'চেম্বারের প্রবেশপথ',
    'Official Signboard': 'অফিসিয়াল সাইনবোর্ড',
    'Client Meeting Desk': 'মক্কেল বৈঠকের ডেস্ক',
    'Chamber Consultation': 'চেম্বারে পরামর্শ',
    'Chamber Consultation Desk': 'চেম্বার পরামর্শ ডেস্ক',
    'Advocate Achche Lal Gautam ready for direct client consultations and document reviews at his Unnao office desk.': 'অ্যাডভোকেট অচ্ছে লাল গৌতম উন্নাও অফিসে সরাসরি পরামর্শ ও নথি পর্যালোচনার জন্য উপলব্ধ।',
    'Client Desk': 'মক্কেল ডেস্ক',
    'Case Review': 'মামলা পর্যালোচনা',
    'Legal Advice': 'আইনি পরামর্শ',
    'High Court Judicial Felicitation': 'হাইকোর্টের বিচারিক সম্মাননা',
    'Advocate Achche Lal Gautam presenting ceremonial memento and shawl honoring Hon\'ble High Court Justice Irshad Ali (Lucknow Bench) at the Oath Ceremony.': 'শপথগ্রহণ অনুষ্ঠানে অ্যাডভোকেট অচ্ছে লাল গৌতম মাননীয় হাইকোর্টের বিচারপতি ইরশাদ আলি (লখনউ বেঞ্চ)-কে স্মারক ও শাল দিয়ে সম্মান জানাচ্ছেন।',
    'Lucknow Bench': 'লখনউ বেঞ্চ',
    'Hon\'ble Justice Irshad Ali': 'মাননীয় বিচারপতি ইরশাদ আলি',
    'Oath Ceremony': 'শপথগ্রহণ অনুষ্ঠান',
    'Office Consultation': 'অফিসে পরামর্শ',
    'Client Consultation & Legal Advisory': 'মক্কেল পরামর্শ ও আইনি দিকনির্দেশনা',
    'Direct client consultation, case discussion, and legal document verification in progress.': 'সরাসরি মক্কেল পরামর্শ, মামলা আলোচনা এবং আইনি নথি যাচাই চলছে।',
    'Client Advisory': 'মক্কেল পরামর্শ',
    'Case Discussion': 'মামলা আলোচনা',
    'Document Verification': 'নথি যাচাই',
    'Lead Advocate': 'প্রধান আইনজীবী',
    'Lead counsel handling criminal trials, land consolidation (चकबंदी), revenue appeals, and matrimonial cases with personalized guidance.': 'ফৌজদারি বিচার, চকমবন্দি, রাজস্ব আপিল এবং বিবাহ সংক্রান্ত বিষয়ে ব্যক্তিগত দিকনির্দেশনা প্রদানকারী প্রধান আইনজীবী।',
    'District Court Unnao': 'উন্নাও জেলা আদালত',
    'Legal Counsel': 'আইনি পরামর্শদাতা',
    'How it works': 'কীভাবে কাজ করে',
    'From first call to clear next steps.': 'প্রথম ফোন থেকে পরবর্তী স্পষ্ট পদক্ষেপ পর্যন্ত।',
    'Share the facts': 'ঘটনাগুলি জানান',
    'Tell us the nature of the matter and what has happened.': 'বিষয়টির ধরন এবং কী ঘটেছে তা জানান।',
    'Review & consultation': 'পর্যালোচনা ও পরামর্শ',
    'Discuss documents, timelines and the available legal route.': 'নথি, সময়সীমা এবং উপলব্ধ আইনি পথ নিয়ে আলোচনা করুন।',
    'Case action': 'মামলার পদক্ষেপ',
    'Proceed with the appropriate representation, filings or next step.': 'উপযুক্ত প্রতিনিধিত্ব, আবেদন বা পরবর্তী পদক্ষেপ নিয়ে এগিয়ে যান।',
    'Team & Mentorship': 'দল ও পরামর্শদান',
    'Guided Legal Minds.': 'দিকনির্দেশনায় গড়ে ওঠা আইনি মন।',
    'These advocates are my juniors. They work, learn, and grow under my direct guidance, ensuring thorough research and dedicated support for our clients.': 'এই আইনজীবীরা আমার জুনিয়র। তাঁরা আমার সরাসরি দিকনির্দেশনায় কাজ করেন, শেখেন ও এগিয়ে যান; মক্কেলদের জন্য গভীর গবেষণা ও নিবেদিত সহায়তা নিশ্চিত করেন।',
    'LL.B. • JUNIOR ASSOCIATE': 'এলএল.বি. • জুনিয়র সহযোগী',
    'Assisting in case preparation, legal research, and district court proceedings under continuous mentorship.': 'নিয়মিত দিকনির্দেশনায় মামলা প্রস্তুতি, আইনি গবেষণা এবং জেলা আদালতের কার্যক্রমে সহায়তা।',
    'Consultation': 'পরামর্শ',
    'Tell us about your matter.': 'আপনার বিষয়টি জানান।',
    'Submit a consultation request. Requests are saved in this browser and work without a server.': 'পরামর্শের অনুরোধ পাঠান। অনুরোধগুলি এই ব্রাউজারে সংরক্ষিত হয় এবং সার্ভার ছাড়াই কাজ করে।',
    'By appointment': 'সময় নির্ধারণ করে',
    'Near SDM Judicial Court Collectorate, Kachari Parisar, Unnao, Uttar Pradesh 209801': 'এসডিএম জুডিশিয়াল কোর্ট কালেক্টরেটের কাছে, কাছারি পরিসর, উন্নাও, উত্তর প্রদেশ 209801',
    '(Chamber Helpline)': '(চেম্বার হেল্পলাইন)',
    CONTACT: 'যোগাযোগ',
    'District Court Lawyer • Unnao': 'উন্নাও জেলা আদালতের আইনজীবী',
    'Request a consultation →': 'পরামর্শের অনুরোধ করুন →',
    'Achche Lal Gautam. District Court Lawyer, Unnao.': 'অচ্ছে লাল গৌতম। উন্নাও জেলা আদালতের আইনজীবী।',
    'Your name': 'আপনার নাম',
    'Phone number': 'ফোন নম্বর',
    'Briefly describe your matter': 'আপনার বিষয়টি সংক্ষেপে লিখুন',
    Name: 'নাম',
    Phone: 'ফোন',
    'Practice area': 'আইনি ক্ষেত্র',
    'Criminal Law': 'ফৌজদারি আইন',
    'Land & Property': 'জমি ও সম্পত্তি',
    'Marriage & Family': 'বিবাহ ও পরিবার',
    'Civil Disputes': 'দেওয়ানি বিরোধ',
    Other: 'অন্যান্য',
    'Brief message': 'সংক্ষিপ্ত বার্তা',
    'Saved consultation requests': 'সংরক্ষিত পরামর্শের অনুরোধ',
    'No requests saved in this browser.': 'এই ব্রাউজারে কোনো অনুরোধ সংরক্ষিত নেই।',
    Delete: 'মুছুন',
  },
};

function translate(lang: Lang, text: string): string {
  if (lang === 'en') return text;
  return TRANSLATIONS[lang]?.[text] ?? text;
}

const translatedTextNodes = new WeakMap<Text, { original: string; last: string }>();
const translatedAttributes = new WeakMap<Element, Map<string, { original: string; last: string }>>();

function applyTranslations(lang: Lang) {
  if (typeof document === 'undefined') return;

  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  let node: Node | null;
  while ((node = walker.nextNode())) {
    const textNode = node as Text;
    const parent = textNode.parentElement;
    const current = textNode.data;
    if (!parent || !current.trim() || parent.closest('.lang-switcher,script,style')) continue;

    const previous = translatedTextNodes.get(textNode);
    const original = previous && current === previous.last ? previous.original : current;
    const trimmed = original.trim();
    const leading = original.slice(0, original.indexOf(trimmed));
    const trailing = original.slice(original.indexOf(trimmed) + trimmed.length);
    const translated = lang === 'en' ? original : `${leading}${translate(lang, trimmed)}${trailing}`;

    if (current !== translated) textNode.data = translated;
    translatedTextNodes.set(textNode, { original, last: translated });
  }

  document.querySelectorAll('[placeholder], [aria-label], [title]').forEach((element) => {
    if (element.closest('.lang-switcher')) return;

    let attributes = translatedAttributes.get(element);
    if (!attributes) {
      attributes = new Map();
      translatedAttributes.set(element, attributes);
    }

    for (const name of ['placeholder', 'aria-label', 'title']) {
      const current = element.getAttribute(name);
      if (current === null) continue;

      const previous = attributes.get(name);
      const original = previous && current === previous.last ? previous.original : current;
      const translated = lang === 'en' ? original : translate(lang, original);
      if (current !== translated) element.setAttribute(name, translated);
      attributes.set(name, { original, last: translated });
    }
  });
}

export default function LangSwitcher() {
  const [lang, setLang] = useState<Lang>('en');

  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ur' ? 'rtl' : 'ltr';
    applyTranslations(lang);

    const observer = new MutationObserver(() => applyTranslations(lang));
    observer.observe(document.body, {
      attributes: true,
      attributeFilter: ['aria-label', 'placeholder', 'title'],
      childList: true,
      characterData: true,
      subtree: true,
    });
    return () => observer.disconnect();
  }, [lang]);

  function handleChange(e: React.ChangeEvent<HTMLSelectElement>) {
    const v = e.target.value as Lang;
    setLang(v);
  }

  return (
    <div className="lang-switcher" aria-label="Language selector">
      <span>文</span>
      <select id="languageSelect" value={lang} onChange={handleChange}>
        <option value="en">English</option>
        <option value="hi">हिन्दी</option>
        <option value="pa">ਪੰਜਾਬੀ</option>
        <option value="ur">اردو</option>
        <option value="bn">বাংলা</option>
      </select>
    </div>
  );
}
